// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SightKeeper.Data;

#nullable disable

namespace SightKeeper.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4");

            modelBuilder.Entity("AssetInternalTrainedWeights", b =>
                {
                    b.Property<int>("AssetsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InternalTrainedWeightsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetsId", "InternalTrainedWeightsId");

                    b.HasIndex("InternalTrainedWeightsId");

                    b.ToTable("AssetInternalTrainedWeights");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Common.Asset", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Assets", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Common.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Common.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Images", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Common.ItemClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId");

                    b.ToTable("ItemClasses", (string)null);
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.DataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Models");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Detector.DetectorItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemClassId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("ItemClassId");

                    b.ToTable("DetectorItems", (string)null);
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.ModelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("ModelType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModelConfigs");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DetectorDataSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectorDataSetId");

                    b.HasIndex("GameId");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Screenshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Screenshots", (string)null);
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.ScreenshotsLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAnyScreenshots")
                        .HasColumnType("INTEGER");

                    b.Property<ushort?>("MaxQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ScreenshotsLibraries", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Weights", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TrainedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("ModelId");

                    b.ToTable("Weights");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Weights");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.WeightsLibrary", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ModelWeightsLibraries", (string)null);
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Detector.DetectorAsset", b =>
                {
                    b.HasBaseType("SightKeeper.Domain.Model.Common.Asset");

                    b.Property<int>("DataSetId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("DataSetId");

                    b.ToTable("DetectorAssets", (string)null);
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.ScreenshotImage", b =>
                {
                    b.HasBaseType("SightKeeper.Domain.Model.Common.Image");

                    b.Property<int>("ScreenshotId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ScreenshotId")
                        .IsUnique();

                    b.ToTable("ScreenshotImages", (string)null);
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Detector.DetectorDataSet", b =>
                {
                    b.HasBaseType("SightKeeper.Domain.Model.DataSet");

                    b.ToTable("DetectorModels", (string)null);
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.ModelScreenshotsLibrary", b =>
                {
                    b.HasBaseType("SightKeeper.Domain.Model.ScreenshotsLibrary");

                    b.Property<int>("DataSetId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("DataSetId")
                        .IsUnique();

                    b.ToTable("ModelScreenshotsLibraries", (string)null);
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.InternalTrainedWeights", b =>
                {
                    b.HasBaseType("SightKeeper.Domain.Model.Weights");

                    b.Property<int>("Batch")
                        .HasColumnType("INTEGER");

                    b.Property<float>("BoundingLoss")
                        .HasColumnType("REAL");

                    b.Property<float>("ClassificationLoss")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("InternalTrainedWeights");
                });

            modelBuilder.Entity("AssetInternalTrainedWeights", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.Common.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SightKeeper.Domain.Model.InternalTrainedWeights", null)
                        .WithMany()
                        .HasForeignKey("InternalTrainedWeightsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Common.Asset", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.Screenshot", "Screenshot")
                        .WithOne("Asset")
                        .HasForeignKey("SightKeeper.Domain.Model.Common.Asset", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screenshot");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Common.Image", b =>
                {
                    b.OwnsOne("SightKeeper.Domain.Model.Common.Resolution", "Resolution", b1 =>
                        {
                            b1.Property<int>("ImageId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ImageId");

                            b1.ToTable("Images");

                            b1.WithOwner()
                                .HasForeignKey("ImageId");
                        });

                    b.Navigation("Resolution")
                        .IsRequired();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Common.ItemClass", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.DataSet", "DataSet")
                        .WithMany("ItemClasses")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.DataSet", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.Common.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.OwnsOne("SightKeeper.Domain.Model.Common.Resolution", "Resolution", b1 =>
                        {
                            b1.Property<int>("DataSetId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Height")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Width")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DataSetId");

                            b1.ToTable("Models");

                            b1.WithOwner()
                                .HasForeignKey("DataSetId");
                        });

                    b.Navigation("Game");

                    b.Navigation("Resolution")
                        .IsRequired();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Detector.DetectorItem", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.Detector.DetectorAsset", "Asset")
                        .WithMany("Items")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SightKeeper.Domain.Model.Common.ItemClass", "ItemClass")
                        .WithMany("DetectorItems")
                        .HasForeignKey("ItemClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SightKeeper.Domain.Model.Detector.BoundingBox", "Bounding", b1 =>
                        {
                            b1.Property<int>("DetectorItemId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("Bottom")
                                .HasColumnType("REAL");

                            b1.Property<double>("Left")
                                .HasColumnType("REAL");

                            b1.Property<double>("Right")
                                .HasColumnType("REAL");

                            b1.Property<double>("Top")
                                .HasColumnType("REAL");

                            b1.HasKey("DetectorItemId");

                            b1.ToTable("DetectorItems");

                            b1.WithOwner()
                                .HasForeignKey("DetectorItemId");
                        });

                    b.Navigation("Asset");

                    b.Navigation("Bounding")
                        .IsRequired();

                    b.Navigation("ItemClass");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Profile", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.Detector.DetectorDataSet", "DetectorDataSet")
                        .WithMany()
                        .HasForeignKey("DetectorDataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SightKeeper.Domain.Model.Common.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.Navigation("DetectorDataSet");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Screenshot", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.ScreenshotsLibrary", "Library")
                        .WithMany("Screenshots")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Weights", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.WeightsLibrary", "Library")
                        .WithMany("Weights")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SightKeeper.Domain.Model.ModelConfig", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.WeightsLibrary", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.DataSet", "DataSet")
                        .WithOne("WeightsLibrary")
                        .HasForeignKey("SightKeeper.Domain.Model.WeightsLibrary", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Detector.DetectorAsset", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.Detector.DetectorDataSet", "DataSet")
                        .WithMany("Assets")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SightKeeper.Domain.Model.Common.Asset", null)
                        .WithOne()
                        .HasForeignKey("SightKeeper.Domain.Model.Detector.DetectorAsset", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.ScreenshotImage", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.Common.Image", null)
                        .WithOne()
                        .HasForeignKey("SightKeeper.Domain.Model.ScreenshotImage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SightKeeper.Domain.Model.Screenshot", "Screenshot")
                        .WithOne("Image")
                        .HasForeignKey("SightKeeper.Domain.Model.ScreenshotImage", "ScreenshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Screenshot");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Detector.DetectorDataSet", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.DataSet", null)
                        .WithOne()
                        .HasForeignKey("SightKeeper.Domain.Model.Detector.DetectorDataSet", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.ModelScreenshotsLibrary", b =>
                {
                    b.HasOne("SightKeeper.Domain.Model.DataSet", "DataSet")
                        .WithOne("ScreenshotsLibrary")
                        .HasForeignKey("SightKeeper.Domain.Model.ModelScreenshotsLibrary", "DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SightKeeper.Domain.Model.ScreenshotsLibrary", null)
                        .WithOne()
                        .HasForeignKey("SightKeeper.Domain.Model.ModelScreenshotsLibrary", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Common.ItemClass", b =>
                {
                    b.Navigation("DetectorItems");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.DataSet", b =>
                {
                    b.Navigation("ItemClasses");

                    b.Navigation("ScreenshotsLibrary")
                        .IsRequired();

                    b.Navigation("WeightsLibrary")
                        .IsRequired();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Screenshot", b =>
                {
                    b.Navigation("Asset");

                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.ScreenshotsLibrary", b =>
                {
                    b.Navigation("Screenshots");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.WeightsLibrary", b =>
                {
                    b.Navigation("Weights");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Detector.DetectorAsset", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SightKeeper.Domain.Model.Detector.DetectorDataSet", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
